### ISSUE TITLE
2.1.9 doesn't work with FIPS enabled EKS optimized Bottlerocket AMIs

### ISSUE THREAD

**Issue by krmichelos** [kubernetes-sigs/aws-efs-csi-driver#1661]
/kind bug

**What happened?**
After upgrading to 2.1.9 the driver failed to mount EFS PVs

**What you expected to happen?**
EFS PVs would continue to mount as they did with version 2.1.8

**How to reproduce it (as minimally and precisely as possible)?**
Run a pod that uses an EFS PV on a node based on the AMI listed below with version 2.1.9 of the EFS CSI driver plugin

**Anything else we need to know?**:
Pods in this state have events with errors like this:
`FATAL: Startup failure (dev note: apps_startup()) for openssl
003E8F1FD67F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/lib64/ossl-modules/fips.so): /usr/lib64/ossl-modules/fips.so: cannot open shared object file: No such file or directory
003E8F1FD67F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:147:
003E8F1FD67F0000:error:07880025:common libcrypto routines:provider_init:reason(37):crypto/provider_core.c:949:name=fips
003E8F1FD67F0000:error:0700006D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:276:module=providers, value=provider_sect retcode=-1`

**Environment**
- Kubernetes version (use `kubectl version`): v1.32.5-eks-5d4a308
- Node AMI: ami-0a78cd6255b3985d6 (bottlerocket-aws-k8s-1.32-fips-x86_64-v1.42.0-5ed15786)
- Driver version: 2.1.9

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by ghost** [comment]
I tried to upload the tgz but github was returning a 422.  A zip of the files seems to have worked.
[results.zip](https://github.com/user-attachments/files/21110207/results.zip)

**Comment by dderrickmatheww** [comment]
This is happening with my custom RHEL 8 AMI EKS 1.29 as well.

**Comment by hayden-miller-sp** [comment]
Hit the same issue on a FIPS enabled AL2023 AMI based on the `amazon-eks-node-2023` AMIs. Doing some investigating, I found that the breaking change seems to be in one of the staging images: `public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-python-builder:3.11-al23` https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/Dockerfile#L58C6-L58C95. Build tag `3.11.6-al23` had the openssl libraries (including fips) in the /newroot filesystem. However it is not present in `3.11.11-al23` and newer build tags.

EFS-driver version 2.1.8 still worked despite this, due to the openssl pin in that staged image installing the openssl-libararies: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v2.1.8/Dockerfile#L66. But this was removed in 2.1.9 resulting in the issue.

**Comment by aantonovGBG** [comment]
Confirming the same issue on RHEL 9 STIG EKS 1.32 in FIPS mode
Temporary fix : rolled back efs-csi to v 2.1.**8**

**Comment by Kazulin** [comment]
Getting the same exact errors for daemonsets on 2.1.9 using RHEL 9 custom AMIs - what's the fix, aside from temporarily rolling back to 2.1.8?

**Comment by dankova22** [comment]
Fixed in #1678

**Comment by s1tkrousenick** [comment]
Hello this issue is not resolved. I am facing the same issue and upgraded to 2.1.10 and there is still not fips.so. I had to roll back to 2.1.8 and the issue is resolved

**Comment by ghost** [comment]
> Hello this issue is not resolved. I am facing the same issue and upgraded to 2.1.10 and there is still not fips.so. I had to roll back to 2.1.8 and the issue is resolved

I don't think the fix is included until 2.1.11.  Have you tried that version?

**Comment by s1tkrousenick** [comment]
That version is not available yet, the latest listed is 2.1.10 in the AWS web interface

**Comment by mike-gangl** [comment]
FYI the version is now available in the EKS Addons.

**Comment by tedk-orca** [comment]
@s1tkrousenick do you use amazon-linux-2?

**Comment by s1tkrousenick** [comment]
Bottlerocket FIPS
