### ISSUE TITLE
Access Denied when using Access Points

### ISSUE THREAD

**Issue by jpc2350** [kubernetes-sigs/aws-efs-csi-driver#347]
/kind bug

**What happened?**
Creating a ReadWriteMany persistent volume in EKS using an Access point on a file system produces the following error messages:
  ```
2021-03-04 14:43:18,573 - INFO - version=1.26.3 options={'tls': None, 'rw': None, 'accesspoint': 'fsap-redacted'}
2021-03-04 14:43:19,488 - WARNING - Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
2021-03-04 14:43:19,942 - INFO - Starting TLS tunnel: "/usr/bin/stunnel /var/run/efs/stunnel-config.fs-0205e2f4.var.lib.kubelet.pods.f91bf3bc-95d0-4e52-a1ed-7e351d6ad6f4.volumes.kubernetes.io~csi.efs-pv.mount.20168"
2021-03-04 14:43:20,402 - INFO - Started TLS tunnel, pid: 4401
2021-03-04 14:43:20,403 - INFO - Executing: "/sbin/mount.nfs4 127.0.0.1:/ /var/lib/kubelet/pods/f91bf3bc-95d0-4e52-a1ed-7e351d6ad6f4/volumes/kubernetes.io~csi/efs-pv/mount -o rw,noresvport,nfsvers=4.1,retrans=2,hard,wsize=1048576,timeo=600,rsize=1048576,port=20168"
2021-03-04 14:43:20,952 - ERROR - Failed to mount fs-redacted.efs.us-east-1.amazonaws.com at /var/lib/kubelet/pods/f91bf3bc-95d0-4e52-a1ed-7e351d6ad6f4/volumes/kubernetes.io~csi/efs-pv/mount: returncode=32, stderr="mount.nfs4: access denied by server while mounting 127.0.0.1:/"
```
Creating the same persistent volume without the access point (top-level fs only) mounts correctly.
**What you expected to happen?**
I would expect the access point to mount correctly, especially on the example used (multiple_pods in this repo)

**How to reproduce it (as minimally and precisely as possible)?**
Update the volumeHandle in pv.yaml and add a fs access point id.
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): EKS v1.18 w/ node version 1.18.9
- Driver version: v1.1.0
- Brand new EKS Cluster, latest available EFS and EBS CSI drivers, along with VPC CNI, new IAM roles and policies, new EFS filesystem, Security groups are functional and working.
- EFS and EBS CSI drivers installed using Kustomization method.

**Comment by wongma7** [comment]
Do you have any non-default policies configured for the EFS fs? https://docs.aws.amazon.com/efs/latest/ug/iam-access-control-nfs-efs.html

"The default EFS file system policy grants full access to any client that can connect to the file system using a file system mount target. The default policy is in effect whenever a user-configured file system policy is not in effect, including at file system creation. Whenever the default file system policy is in effect, a DescribeFileSystemPolicy API operation returns a PolicyNotFound response. "

**Comment by jpc2350** [comment]
So I kept getting access denied with no file system policy, so to mount the filesystem i put the following file system policy in place:

```
{
    "Version": "2012-10-17",
    "Id": "efs-policy-wizard-bf808fd1-dab2-43bb-b034-6ee426289261",
    "Statement": [
        {
            "Sid": "efs-statement-f8b29500-97a3-4164-8cef-5214573336c8",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "elasticfilesystem:ClientRootAccess",
                "elasticfilesystem:ClientWrite",
                "elasticfilesystem:ClientMount"
            ],
            "Resource": "arn:aws:elasticfilesystem:us-east-1:<>:file-system/fs-<>",
            "Condition": {
                "Bool": {
                    "elasticfilesystem:AccessedViaMountTarget": "true"
                }
            }
        }
    ]
}
```

The EKS Node IAM role has full access to elasticfilesystem.

**Comment by Skaronator** [comment]
This is the policy I came up with that works on the master branch with dynamic provisioning but I'm not really happy to grant access to all access points arns on that account:

```
data "aws_iam_policy_document" "efs_csi" {
  statement {
    actions = [
      "elasticfilesystem:DescribeFileSystems",
      "elasticfilesystem:CreateAccessPoint",
      "elasticfilesystem:DeleteAccessPoint",
      "elasticfilesystem:DescribeAccessPoints",
    ]
    resources = [aws_efs_file_system.csi.arn, "arn:aws:elasticfilesystem::${data.aws_caller_identity.main.account_id}:access-point/*"]
  }

  statement {
    actions = [
      "elasticfilesystem:ClientRootAccess",
      "elasticfilesystem:ClientWrite",
      "elasticfilesystem:ClientMount",
    ]
    resources = [aws_efs_file_system.csi.arn]
    condition {
      test     = "Bool"
      variable = "elasticfilesystem:AccessedViaMountTarget"
      values   = ["true"]
    }
  }
}
```

Maybe there is a way to limit the ` "arn:aws:elasticfilesystem::${data.aws_caller_identity.main.account_id}:access-point/*"` access-points to a specific EFS arn?

**Comment by wongma7** [comment]
@kbasv do you have any insight on best practices for access point policies? obviously with dynamic provisioning we don't know the names of access points beforehand, is there a way to use tags or something?

**Comment by kbasv** [comment]
@Skaronator [PR 309](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/309) allows adding tags to your access points. You can modify the policy described in [this example](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json) to add additional tags. These tags can be passed in as additional tags from cmd line option [tags](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/cmd/main.go#L44).  The driver appends these tags when it creates access points.

The above tags can be used as a mechanism to limit the driver to access points created by driver.

**Comment by Skaronator** [comment]
I gave this a try and it works perfectly! Thanks @kbasv  and the "workaround" with the tags is actually quite clever ;)

However I did change StringLike to StringEquals ;)

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/4a8153ecbfa12afeb1a62e0aab4aab016d5804c2/docs/iam-policy-example.json#L19

My terraform resource now looks like this if anyone is curious

```hcl
data "aws_iam_policy_document" "efs_csi" {
  statement {
    actions = [
      "elasticfilesystem:DescribeFileSystems",
    ]
    resources = [aws_efs_file_system.csi.arn]
  }

  statement {
    actions = [
      "elasticfilesystem:DescribeAccessPoints",
    ]
    resources = ["*"]
  }

  statement {
    actions = [
      "elasticfilesystem:CreateAccessPoint",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:RequestTag/efs.csi.aws.com/cluster"
      values   = ["true"]
    }
  }

  statement {
    actions = [
      "elasticfilesystem:DeleteAccessPoint",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/efs.csi.aws.com/cluster"
      values   = ["true"]
    }
  }
}
```

**Comment by Skaronator** [comment]
Mh weird. It didn't seem like to work properly all the time with my policy above. The log didn't really helped me but after re-adding this part it seems to work fine again:

```hcl
  statement {
    actions = [
      "elasticfilesystem:ClientRootAccess",
      "elasticfilesystem:ClientWrite",
      "elasticfilesystem:ClientMount",
    ]
    resources = [aws_efs_file_system.csi.arn]
    condition {
      test     = "Bool"
      variable = "elasticfilesystem:AccessedViaMountTarget"
      values   = ["true"]
    }
  }
```

Is that expected?

**Comment by kbelosevic** [comment]
@Skaronator If possible, can you provide an example policy with tags used and also an example how to add this "cmd tags" option for csi driver, having issues figuring out how to add this via helm ?

**Comment by Skaronator** [comment]
@kbelosevic Yeah its basically my last 2 comments together. I'm on holiday this week, so cannot provide the exact policy right now. 

And we don't use custom tags, the default are fine for us.

**Comment by KarstenSiemer** [comment]
I have deployed the driver into several clusters many of which are in the same aws account, so I have personally settled with this:
```
resource "aws_iam_policy" "aws_efs_csi_driver" {
  count  = var.aws_efs_csi_driver_enabled ? 1 : 0
  name   = "aws-efs-csi-driver-${var.name}"
  policy = <<-EOD
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "elasticfilesystem:DescribeAccessPoints",
          "elasticfilesystem:DescribeFileSystems"
        ],
        "Resource": "*"
      },
      {
        "Effect": "Allow",
        "Action": [
          "elasticfilesystem:CreateAccessPoint"
        ],
        "Resource": "*",
        "Condition": {
          "StringLike": {
            "aws:RequestTag/efs.csi.aws.com/cluster": "true",
            "aws:RequestTag/cluster-name": "${var.name}"
          }
        }
      },
      {
        "Effect": "Allow",
        "Action": "elasticfilesystem:DeleteAccessPoint",
        "Resource": "*",
        "Condition": {
          "StringEquals": {
            "aws:ResourceTag/efs.csi.aws.com/cluster": "true",
            "aws:ResourceTag/cluster-name": "${var.name}"
          }
        }
      }
    ]
  }
  EOD
}
```
I have added the cluster-name tag into the drivers deployment by specifying the --tags=cluster-name:name flag like that.
Now they cannot interfere with other clusters access points. This works very well, I am quite pleased

**Comment by cf250024** [comment]
@KarstenSiemer I use the policy above working for you but I still face issues. I even followed https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html manually without luck. Is it possible for you to share the code (terraform code?) for me to try and I can compare with my situation if your code is working for me? Thanks.

**Comment by KarstenSiemer** [comment]
Just a question. I have added a kms key to my aws_efs_file_system to encrypt it. This apparently works as the filesystem also show encrypted in web console. Everything works great since a few weeks and pods happily write into the efs. What I am wondering about now is that the role we defined here isn't including any permissions on the kms key and yet it works.
Can somebody tell me why?

**Comment by kbasv** [comment]
@KarstenSiemer [EFS Encryption document](https://docs.aws.amazon.com/efs/latest/ug/encryption.html) provides more information into how encryption works for EFS.
